-- TARGET: Run after 01_enums.sql. Matches SOURCE column inventory.

-- Tier 0
create table public.memberships (
  id uuid primary key default uuid_generate_v4(),
  tier public.membership_tier_enum,
  status public.membership_status_enum,
  last_renewal date,
  payment_method text,
  is_subscription boolean default false,
  start_date date,
  stripe_customer_id text,
  stripe_subscription_id text,
  stripe_tier_id text,
  customer_email text,
  created_at timestamptz default now()
);

create table public.business_memberships (
  id uuid primary key default gen_random_uuid(),
  status public.membership_status_enum not null,
  last_renewal date not null,
  payment_method text,
  is_subscription boolean default false
);

create table public.qr_codes (
  id uuid primary key default gen_random_uuid(),
  name text,
  url text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.event_templates (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  description text,
  default_field_data jsonb not null default '{}',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.tshirt_preorders (
  id uuid primary key default gen_random_uuid(),
  stripe_checkout_session_id text not null unique,
  stripe_payment_intent_id text,
  customer_name text not null,
  customer_email text not null,
  shipping_address jsonb,
  line_items jsonb not null,
  amount_cents integer not null check (amount_cents >= 0),
  currency text not null default 'usd',
  status text not null default 'pending'
    check (status in ('pending', 'paid', 'refunded', 'failed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.fundraising_donations (
  id uuid primary key default gen_random_uuid(),
  stripe_checkout_session_id text not null unique,
  stripe_payment_intent_id text,
  donation_tier text not null
    check (donation_tier in ('individual', 'household', 'champ', 'custom')),
  amount_cents integer not null check (amount_cents >= 0),
  currency text not null default 'usd',
  customer_email text,
  status text not null default 'pending'
    check (status in ('pending', 'paid', 'refunded', 'failed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.feature_ids (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  feature_id text,
  vote_count bigint,
  surface text,
  constraint unique_feature_surface unique (feature_id, surface)
);

create table public.user_roles (
  user_id uuid primary key references auth.users (id) on delete cascade,
  role text not null check (role in ('admin')),
  created_at timestamptz not null default now()
);

-- Tier 1
create table public.people (
  id uuid primary key default uuid_generate_v4(),
  full_name text not null,
  email text unique,
  address text,
  phone text,
  roles text[],
  tags text[],
  source text,
  created_at timestamptz default now(),
  membership_id uuid references public.memberships (id) on delete set null,
  website_source text,
  is_executive_board boolean not null default false
);

create table public.businesses (
  id uuid primary key default uuid_generate_v4(),
  business_name text,
  contact_name text,
  email text,
  phone text,
  address text,
  membership_id uuid references public.business_memberships (id) on delete set null,
  notes text,
  website text,
  google_place_id text,
  contacted boolean not null default false,
  hidden boolean not null default false,
  is_member boolean not null default false,
  is_past_sponsor boolean not null default false
);

create table public.leaflets (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  distribution_date date not null,
  status public.leaflet_status not null default 'planned',
  activated_at timestamptz,
  closed_at timestamptz,
  print_cost_cents integer,
  membership_qr_code_id uuid references public.qr_codes (id) on delete set null,
  comm_initial_confirmation_sent_at timestamptz,
  comm_distribution_day_pickup_sent_at timestamptz,
  comm_delivery_complete_prompt_sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Tier 2
create table public.events (
  id uuid primary key default uuid_generate_v4(),
  name text,
  date date,
  event_template_id uuid references public.event_templates (id) on delete set null,
  starts_at timestamptz,
  ends_at timestamptz,
  slug text,
  field_data jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.routes (
  id uuid primary key default uuid_generate_v4(),
  route_name text not null,
  leaflet_count integer,
  created_at timestamptz default now(),
  route_type public."Route Types",
  primary_deliverer_id uuid references public.people (id) on delete set null,
  primary_deliverer_email text,
  building_contact_name text,
  building_contact_email text,
  building_contact_phone text,
  building_contact_is_deliverer boolean not null default false
);

create table public.task_templates (
  id uuid primary key default gen_random_uuid(),
  context public.workflow_context not null,
  event_template_id uuid references public.event_templates (id) on delete cascade,
  title text not null,
  description text,
  offset_days integer not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint task_templates_context_check check (
    (context = 'leaflet' and event_template_id is null)
    or context = 'event'
    or (context = 'membership' and event_template_id is null)
  )
);

create table public.comm_settings (
  id uuid primary key default gen_random_uuid(),
  context public.workflow_context not null,
  event_template_id uuid references public.event_templates (id) on delete cascade,
  name text not null,
  step_key text not null,
  resend_template_id text not null,
  trigger public.comm_trigger not null default 'anchor_offset',
  offset_days integer,
  offset_time time not null default '09:00:00',
  requires_response boolean not null default false,
  is_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint comm_settings_offset_days_check check (
    trigger = 'on_activate'
    or offset_days is not null
  )
);

create table public.volunteer_asks (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  commitment_type public.volunteer_commitment_type not null,
  commitment_unit public.volunteer_commitment_unit not null,
  commitment_quantity numeric(10, 2) not null check (commitment_quantity > 0),
  quantity integer not null check (quantity > 0),
  event_id uuid references public.events (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.committee_default_attendees (
  id uuid primary key default gen_random_uuid(),
  committee_slug public.committee_slug not null,
  person_id uuid not null references public.people (id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint committee_default_attendees_committee_person_unique unique (committee_slug, person_id)
);

-- Tier 3
create table public.tasks (
  id uuid primary key default gen_random_uuid(),
  context public.workflow_context not null,
  context_id uuid not null,
  template_id uuid references public.task_templates (id) on delete set null,
  title text not null,
  description text,
  offset_days integer not null,
  is_complete boolean not null default false,
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.deliveries (
  id uuid primary key default gen_random_uuid(),
  person_id uuid references public.people (id) on delete set null,
  route_id uuid not null references public.routes (id) on delete cascade,
  date_delivered date,
  leaflet_id uuid references public.leaflets (id) on delete cascade,
  leaflet_count integer,
  is_skipped boolean not null default false,
  response public.delivery_response not null default 'pending',
  responded_at timestamptz,
  leaflets_delivered integer,
  leaflets_leftover integer,
  building_contact_name text,
  building_contact_email text,
  building_contact_phone text,
  building_contact_is_deliverer boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  comm_pre_distribution_reminder_sent_at timestamptz,
  comm_completion_followup_sent_at timestamptz
);

create table public.sponsorships (
  business_id uuid references public.businesses (id) on delete cascade,
  event_id uuid references public.events (id) on delete set null,
  amount numeric(10, 2),
  status text check (status in ('pledged', 'invoiced', 'paid')),
  memo text,
  paid_date date,
  id uuid primary key default gen_random_uuid(),
  leaflet_id uuid references public.leaflets (id) on delete cascade,
  description text,
  image_url text,
  quantity integer not null default 1,
  constraint sponsorships_one_parent_check check (
    not (leaflet_id is not null and event_id is not null)
  )
);

create table public.event_volunteers (
  id uuid primary key default uuid_generate_v4(),
  event_id uuid references public.events (id) on delete cascade,
  person_id uuid references public.people (id) on delete cascade,
  created_at timestamptz default now()
);

create table public.payments (
  id uuid primary key default gen_random_uuid(),
  person_id uuid references public.people (id) on delete set null,
  membership_id uuid references public.memberships (id) on delete set null,
  amount numeric(10, 2) not null,
  date date not null,
  memo text,
  type public.payment_type_enum not null,
  method public.payment_method_enum not null,
  stripe_transaction_id text
);

create table public.committee_meetings (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null unique references public.events (id) on delete cascade,
  committee public.committee_slug not null,
  location_type public.meeting_location_type not null default 'in_person',
  location text,
  google_calendar_url text,
  agenda_json jsonb,
  raw_transcript text,
  structured_minutes jsonb,
  minutes_status public.minutes_status not null default 'draft',
  minutes_error text,
  submitted_at timestamptz,
  submitted_by uuid,
  website_slug text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Tier 4
create table public.volunteers (
  id uuid primary key default gen_random_uuid(),
  volunteer_ask_id uuid not null references public.volunteer_asks (id) on delete cascade,
  person_id uuid not null references public.people (id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (volunteer_ask_id, person_id)
);

create table public.committee_meeting_attendees (
  id uuid primary key default gen_random_uuid(),
  meeting_id uuid not null references public.committee_meetings (id) on delete cascade,
  person_id uuid not null references public.people (id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (meeting_id, person_id)
);

create table public.action_items (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  assignee_person_id uuid references public.people (id) on delete set null,
  committee_meeting_id uuid references public.committee_meetings (id) on delete cascade,
  status public.action_item_status not null default 'open',
  due_at date,
  source public.action_item_source not null default 'manual',
  sort_order integer not null default 0,
  completed_at timestamptz,
  completed_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
