import { Invoice } from "./types";

export const invoices: Invoice[] = [
  { id: 1, dueDate: "Mar 23", dueRel: "27 days ago", status: "Overdue", customer: "Breakout Studios", email: "accounting@breakout.stu...", amount: "$2,625", cents: "00", invoiceNo: "INV-11", invoiceDate: "Feb 18", type: "One time", sentTo: "accounting@breakout.studio", createdBy: "MEGAN L.", createdDate: "FEB 18", autoReminders: "Off", recurring: "One time" },
  { id: 2, dueDate: "Apr 2",  dueRel: "17 days ago", status: "Overdue", customer: "Breakout Studios", email: "accounting@breakout.stu...", amount: "$1,425", cents: "00", invoiceNo: "INV-12", invoiceDate: "Mar 3",  type: "One time", sentTo: "accounting@breakout.studio", createdBy: "MEGAN L.", createdDate: "MAR 3",  autoReminders: "Off", recurring: "One time" },
  { id: 3, dueDate: "Apr 5",  dueRel: "14 days ago", status: "Overdue", customer: "Breakout Studios", email: "accounting@breakout.stu...", amount: "$75",    cents: "00", invoiceNo: "INV-13", invoiceDate: "Mar 6",  type: "One time", sentTo: "accounting@breakout.studio", createdBy: "MEGAN L.", createdDate: "MAR 6",  autoReminders: "Off", recurring: "One time" },
  { id: 4, dueDate: "Apr 22", dueRel: "in 3 days",   status: "Active",  customer: "Breakout Studios", email: "accounting@breakout.stu...", amount: "$1,200", cents: "00", invoiceNo: "INV-16", invoiceDate: "Mar 23", type: "One time", sentTo: "accounting@breakout.studio", createdBy: "MEGAN L.", createdDate: "MAR 23", autoReminders: "On",  recurring: "One time" },
  { id: 5, dueDate: "Apr 22", dueRel: "in 3 days",   status: "Active",  customer: "GroundGame.Health", email: "Berkley.N@groundgame.h...", amount: "$37",    cents: "50", invoiceNo: "INV-17", invoiceDate: "Mar 23", type: "One time", sentTo: "Berkley.N@groundgame.health", createdBy: "MEGAN L.", createdDate: "MAR 23", autoReminders: "Off", recurring: "One time" },
  { id: 6, dueDate: "May 10", dueRel: "in 21 days",  status: "Active",  customer: "Breakout Studios", email: "accounting@breakout.stu...", amount: "$75",    cents: "00", invoiceNo: "INV-19", invoiceDate: "Apr 10", type: "One time", sentTo: "accounting@breakout.studio", createdBy: "MEGAN L.", createdDate: "APR 10", autoReminders: "Off", recurring: "One time" },
  { id: 7, dueDate: "Mar 25", dueRel: "",             status: "Paid",    customer: "Outsourced Complia…", email: "joe@compliancegroupllc....", amount: "$675",   cents: "00", invoiceNo: "INV-10", invoiceDate: "Feb 17", type: "One time", sentTo: "joe@compliancegroupllc.com", createdBy: "MEGAN L.", createdDate: "FEB 17", autoReminders: "Off", recurring: "One time" },
  { id: 8, dueDate: "Jan 20", dueRel: "",             status: "Paid",    customer: "Blessings International", email: "mbriggs@blessing.org", amount: "$1,400", cents: "00", invoiceNo: "INV-6",  invoiceDate: "Jan 14", type: "One time", sentTo: "mbriggs@blessing.org",      createdBy: "MEGAN L.", createdDate: "JAN 14", autoReminders: "Off", recurring: "One time" },
  { id: 9, dueDate: "Mar 30", dueRel: "",             status: "Paid",    customer: "Ken Young",            email: "ken@woodbatbrand.com",     amount: "$1,275", cents: "00", invoiceNo: "INV-14", invoiceDate: "Mar 18", type: "One time", sentTo: "ken@woodbatbrand.com",       createdBy: "MEGAN L.", createdDate: "MAR 18", autoReminders: "Off", recurring: "One time" },
];
