"use client";
import React from "react";
import * as _Builtin from "./_Builtin";
import * as _utils from "./utils";
import _styles from "./CommitteesMain.module.css";

export function CommitteesMain({
  as: _Component = _Builtin.Block,
  c90346Bd65D00575F03B554236A4C6F1 = true,
}) {
  return (
    <_Component
      className={_utils.cx(_styles, "section_home_committees-main")}
      tag="section"
    >
      <_Builtin.Block
        className={_utils.cx(_styles, "padding-global")}
        tag="div"
      >
        <_Builtin.Block
          className={_utils.cx(_styles, "container-large")}
          tag="div"
        >
          <_Builtin.Block
            className={_utils.cx(_styles, "padding-section-large")}
            tag="div"
          >
            <_Builtin.Block
              className={_utils.cx(_styles, "home_committees-main_component")}
              tag="div"
            >
              <_Builtin.Block
                className={_utils.cx(
                  _styles,
                  "margin-bottom",
                  "margin-xxlarge"
                )}
                tag="div"
              >
                <_Builtin.Block
                  className={_utils.cx(
                    _styles,
                    "committees-main_heading-wreap"
                  )}
                  tag="div"
                >
                  <_Builtin.Block
                    className={_utils.cx(
                      _styles,
                      "margin-bottom",
                      "margin-xsmall"
                    )}
                    id={_utils.cx(
                      _styles,
                      "w-node-c10448bf-9a86-9bdc-d767-6e943f1d6523-6542f18a"
                    )}
                    tag="div"
                  >
                    <_Builtin.Heading
                      className={_utils.cx(_styles, "heading-style-h2")}
                      tag="h2"
                    >
                      {"It's your neighborhood, make it what you want"}
                    </_Builtin.Heading>
                  </_Builtin.Block>
                  <_Builtin.Block
                    className={_utils.cx(
                      _styles,
                      "margin-bottom",
                      "margin-small"
                    )}
                    id={_utils.cx(
                      _styles,
                      "w-node-_81c1960c-206d-0697-cfdd-abb6ff315ab3-6542f18a"
                    )}
                    tag="div"
                  >
                    <_Builtin.Paragraph
                      id={_utils.cx(
                        _styles,
                        "w-node-aa3e0b6d-cd30-931f-8d00-252f1029850f-6542f18a"
                      )}
                    >
                      {
                        "Whether you have 15 hours or 15 minutes a month, you can help shape your local community through our different committees that meet and get things done."
                      }
                    </_Builtin.Paragraph>
                  </_Builtin.Block>
                </_Builtin.Block>
              </_Builtin.Block>
              <_Builtin.SliderWrapper
                className={_utils.cx(_styles, "home_committees-main_group")}
                data-animation="slide"
                data-duration="500"
                navSpacing={3}
                navInvert={false}
                animation="slide"
                easing="ease"
                duration={500}
                infinite={false}
                disableSwipe={false}
                autoplay={false}
                delay={4000}
                autoMax={0}
                hideArrows={false}
                navRound={true}
                navNumbers={false}
                navShadow={false}
                iconArrows={true}
              >
                <_Builtin.SliderMask
                  className={_utils.cx(_styles, "home_committees-main_mask")}
                >
                  <_Builtin.SliderSlide
                    className={_utils.cx(_styles, "home_committees-main_slide")}
                    tag="div"
                  >
                    <_Builtin.Block
                      className={_utils.cx(
                        _styles,
                        "home_committees-main_item"
                      )}
                      tag="div"
                    >
                      <_Builtin.Link
                        className={_utils.cx(
                          _styles,
                          "home_committees-main_item-link"
                        )}
                        button={false}
                        block="inline"
                        options={{
                          href: "#",
                        }}
                      >
                        <_Builtin.Block
                          className={_utils.cx(_styles, "absolute_shade")}
                          tag="div"
                        />
                        <_Builtin.Block
                          className={_utils.cx(
                            _styles,
                            "home_committees-main_item-content"
                          )}
                          tag="div"
                        >
                          <_Builtin.Block
                            className={_utils.cx(
                              _styles,
                              "home_committees-main_item-content-top"
                            )}
                            tag="div"
                          >
                            <_Builtin.Block
                              className={_utils.cx(
                                _styles,
                                "margin-bottom",
                                "margin-xsmall"
                              )}
                              tag="div"
                            >
                              <_Builtin.Block
                                className={_utils.cx(
                                  _styles,
                                  "home_committees-main_meta-wrapper"
                                )}
                                tag="div"
                              >
                                <_Builtin.Block
                                  className={_utils.cx(_styles, "tag")}
                                  tag="div"
                                >
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "text-size-tiny"
                                    )}
                                    tag="div"
                                  >
                                    {"Events committee"}
                                  </_Builtin.Block>
                                </_Builtin.Block>
                              </_Builtin.Block>
                            </_Builtin.Block>
                            <_Builtin.Block tag="div">
                              <_Builtin.Block
                                className={_utils.cx(
                                  _styles,
                                  "margin-bottom",
                                  "margin-xxsmall"
                                )}
                                tag="div"
                              >
                                <_Builtin.Heading
                                  className={_utils.cx(
                                    _styles,
                                    "heading-style-h5"
                                  )}
                                  tag="h3"
                                >
                                  {"Plan events for the neighborhood"}
                                </_Builtin.Heading>
                              </_Builtin.Block>
                              <_Builtin.Block
                                className={_utils.cx(
                                  _styles,
                                  "text-size-regular"
                                )}
                                tag="div"
                              >
                                {
                                  "Bring neighbors together with well through events and connections."
                                }
                              </_Builtin.Block>
                            </_Builtin.Block>
                          </_Builtin.Block>
                        </_Builtin.Block>
                        <_Builtin.Block
                          className={_utils.cx(
                            _styles,
                            "home_committees-main_image-wrapper"
                          )}
                          tag="div"
                        >
                          <_Builtin.Image
                            className={_utils.cx(
                              _styles,
                              "home_committees-main_image"
                            )}
                            loading="lazy"
                            width="auto"
                            height="auto"
                            alt=""
                            src="https://cdn.prod.website-files.com/67f474b29211e3047d6a314e/67f48b519939effcfdec35a2_image1.jpeg"
                          />
                        </_Builtin.Block>
                      </_Builtin.Link>
                    </_Builtin.Block>
                  </_Builtin.SliderSlide>
                  <_Builtin.SliderSlide
                    className={_utils.cx(_styles, "home_committees-main_slide")}
                    tag="div"
                  >
                    <_Builtin.Block
                      className={_utils.cx(
                        _styles,
                        "home_committees-main_item"
                      )}
                      tag="div"
                    >
                      <_Builtin.Link
                        className={_utils.cx(
                          _styles,
                          "home_committees-main_item-link"
                        )}
                        button={false}
                        block="inline"
                        options={{
                          href: "#",
                        }}
                      >
                        <_Builtin.Block
                          className={_utils.cx(_styles, "absolute_shade")}
                          tag="div"
                        />
                        <_Builtin.Block
                          className={_utils.cx(
                            _styles,
                            "home_committees-main_item-content"
                          )}
                          tag="div"
                        >
                          <_Builtin.Block
                            className={_utils.cx(
                              _styles,
                              "home_committees-main_item-content-top"
                            )}
                            tag="div"
                          >
                            <_Builtin.Block
                              className={_utils.cx(
                                _styles,
                                "margin-bottom",
                                "margin-xsmall"
                              )}
                              tag="div"
                            >
                              <_Builtin.Block
                                className={_utils.cx(
                                  _styles,
                                  "home_committees-main_meta-wrapper"
                                )}
                                tag="div"
                              >
                                <_Builtin.Block
                                  className={_utils.cx(_styles, "tag")}
                                  tag="div"
                                >
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "text-size-tiny"
                                    )}
                                    tag="div"
                                  >
                                    {"Communications committee"}
                                  </_Builtin.Block>
                                </_Builtin.Block>
                              </_Builtin.Block>
                            </_Builtin.Block>
                            <_Builtin.Block tag="div">
                              <_Builtin.Block
                                className={_utils.cx(
                                  _styles,
                                  "margin-bottom",
                                  "margin-xxsmall"
                                )}
                                tag="div"
                              >
                                <_Builtin.Heading
                                  className={_utils.cx(
                                    _styles,
                                    "heading-style-h5"
                                  )}
                                  tag="h3"
                                >
                                  {"Get the word out"}
                                </_Builtin.Heading>
                              </_Builtin.Block>
                              <_Builtin.Block
                                className={_utils.cx(
                                  _styles,
                                  "text-size-regular"
                                )}
                                tag="div"
                              >
                                {
                                  "Bring neighbors together with well through events and connections."
                                }
                              </_Builtin.Block>
                            </_Builtin.Block>
                          </_Builtin.Block>
                        </_Builtin.Block>
                        <_Builtin.Block
                          className={_utils.cx(
                            _styles,
                            "home_committees-main_image-wrapper"
                          )}
                          tag="div"
                        >
                          <_Builtin.Image
                            className={_utils.cx(
                              _styles,
                              "home_committees-main_image"
                            )}
                            loading="lazy"
                            width="auto"
                            height="auto"
                            alt=""
                            src="https://cdn.prod.website-files.com/67f474b29211e3047d6a314e/67f48b51ec064ef3e630383e_community-meeting.jpeg"
                          />
                        </_Builtin.Block>
                      </_Builtin.Link>
                    </_Builtin.Block>
                  </_Builtin.SliderSlide>
                  <_Builtin.SliderSlide
                    className={_utils.cx(_styles, "home_committees-main_slide")}
                    tag="div"
                  >
                    <_Builtin.Block
                      className={_utils.cx(
                        _styles,
                        "home_committees-main_item"
                      )}
                      tag="div"
                    >
                      <_Builtin.Link
                        className={_utils.cx(
                          _styles,
                          "home_committees-main_item-link"
                        )}
                        button={false}
                        block="inline"
                        options={{
                          href: "#",
                        }}
                      >
                        <_Builtin.Block
                          className={_utils.cx(_styles, "absolute_shade")}
                          tag="div"
                        />
                        <_Builtin.Block
                          className={_utils.cx(
                            _styles,
                            "home_committees-main_item-content"
                          )}
                          tag="div"
                        >
                          <_Builtin.Block
                            className={_utils.cx(
                              _styles,
                              "home_committees-main_item-content-top"
                            )}
                            tag="div"
                          >
                            <_Builtin.Block
                              className={_utils.cx(
                                _styles,
                                "margin-bottom",
                                "margin-xsmall"
                              )}
                              tag="div"
                            >
                              <_Builtin.Block
                                className={_utils.cx(
                                  _styles,
                                  "home_committees-main_meta-wrapper"
                                )}
                                tag="div"
                              >
                                <_Builtin.Block
                                  className={_utils.cx(_styles, "tag")}
                                  tag="div"
                                >
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "text-size-tiny"
                                    )}
                                    tag="div"
                                  >
                                    {"Silent Book Club"}
                                  </_Builtin.Block>
                                </_Builtin.Block>
                              </_Builtin.Block>
                            </_Builtin.Block>
                            <_Builtin.Block tag="div">
                              <_Builtin.Block
                                className={_utils.cx(
                                  _styles,
                                  "margin-bottom",
                                  "margin-xxsmall"
                                )}
                                tag="div"
                              >
                                <_Builtin.Heading
                                  className={_utils.cx(
                                    _styles,
                                    "heading-style-h5"
                                  )}
                                  tag="h3"
                                >
                                  {"Read together"}
                                </_Builtin.Heading>
                              </_Builtin.Block>
                              <_Builtin.Block
                                className={_utils.cx(
                                  _styles,
                                  "text-size-regular"
                                )}
                                tag="div"
                              >
                                {
                                  "Bring neighbors together with well through events and connections."
                                }
                              </_Builtin.Block>
                            </_Builtin.Block>
                          </_Builtin.Block>
                        </_Builtin.Block>
                        <_Builtin.Block
                          className={_utils.cx(
                            _styles,
                            "home_committees-main_image-wrapper"
                          )}
                          tag="div"
                        >
                          <_Builtin.Image
                            className={_utils.cx(
                              _styles,
                              "home_committees-main_image"
                            )}
                            loading="lazy"
                            width="auto"
                            height="auto"
                            alt=""
                            src="https://cdn.prod.website-files.com/67f474b29211e3047d6a314e/67f48b519939effcfdec35a2_image1.jpeg"
                          />
                        </_Builtin.Block>
                      </_Builtin.Link>
                    </_Builtin.Block>
                  </_Builtin.SliderSlide>
                  <_Builtin.SliderSlide
                    className={_utils.cx(_styles, "home_committees-main_slide")}
                    tag="div"
                  >
                    <_Builtin.Block
                      className={_utils.cx(
                        _styles,
                        "home_committees-main_item"
                      )}
                      tag="div"
                    >
                      <_Builtin.Link
                        className={_utils.cx(
                          _styles,
                          "home_committees-main_item-link"
                        )}
                        button={false}
                        block="inline"
                        options={{
                          href: "#",
                        }}
                      >
                        <_Builtin.Block
                          className={_utils.cx(_styles, "absolute_shade")}
                          tag="div"
                        />
                        <_Builtin.Block
                          className={_utils.cx(
                            _styles,
                            "home_committees-main_item-content"
                          )}
                          tag="div"
                        >
                          <_Builtin.Block
                            className={_utils.cx(
                              _styles,
                              "home_committees-main_item-content-top"
                            )}
                            tag="div"
                          >
                            <_Builtin.Block
                              className={_utils.cx(
                                _styles,
                                "margin-bottom",
                                "margin-xsmall"
                              )}
                              tag="div"
                            >
                              <_Builtin.Block
                                className={_utils.cx(
                                  _styles,
                                  "home_committees-main_meta-wrapper"
                                )}
                                tag="div"
                              >
                                <_Builtin.Block
                                  className={_utils.cx(_styles, "tag")}
                                  tag="div"
                                >
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "text-size-tiny"
                                    )}
                                    tag="div"
                                  >
                                    {"Business committee"}
                                  </_Builtin.Block>
                                </_Builtin.Block>
                              </_Builtin.Block>
                            </_Builtin.Block>
                            <_Builtin.Block tag="div">
                              <_Builtin.Block
                                className={_utils.cx(
                                  _styles,
                                  "margin-bottom",
                                  "margin-xxsmall"
                                )}
                                tag="div"
                              >
                                <_Builtin.Heading
                                  className={_utils.cx(
                                    _styles,
                                    "heading-style-h5"
                                  )}
                                  tag="h3"
                                >
                                  {"Build a thriving business district"}
                                </_Builtin.Heading>
                              </_Builtin.Block>
                              <_Builtin.Block
                                className={_utils.cx(
                                  _styles,
                                  "text-size-regular"
                                )}
                                tag="div"
                              >
                                {
                                  "Bring neighbors together with well through events and connections."
                                }
                              </_Builtin.Block>
                            </_Builtin.Block>
                          </_Builtin.Block>
                        </_Builtin.Block>
                        <_Builtin.Block
                          className={_utils.cx(
                            _styles,
                            "home_committees-main_image-wrapper"
                          )}
                          tag="div"
                        >
                          <_Builtin.Image
                            className={_utils.cx(
                              _styles,
                              "home_committees-main_image"
                            )}
                            loading="lazy"
                            width="auto"
                            height="auto"
                            alt=""
                            src="https://cdn.prod.website-files.com/67f474b29211e3047d6a314e/67f48b519939effcfdec35a2_image1.jpeg"
                          />
                        </_Builtin.Block>
                      </_Builtin.Link>
                    </_Builtin.Block>
                  </_Builtin.SliderSlide>
                  <_Builtin.SliderSlide
                    className={_utils.cx(_styles, "home_committees-main_slide")}
                    tag="div"
                  >
                    <_Builtin.Block
                      className={_utils.cx(
                        _styles,
                        "home_committees-main_item"
                      )}
                      tag="div"
                    >
                      <_Builtin.Link
                        className={_utils.cx(
                          _styles,
                          "home_committees-main_item-link"
                        )}
                        button={false}
                        block="inline"
                        options={{
                          href: "#",
                        }}
                      >
                        <_Builtin.Block
                          className={_utils.cx(_styles, "absolute_shade")}
                          tag="div"
                        />
                        <_Builtin.Block
                          className={_utils.cx(
                            _styles,
                            "home_committees-main_item-content"
                          )}
                          tag="div"
                        >
                          <_Builtin.Block
                            className={_utils.cx(
                              _styles,
                              "home_committees-main_item-content-top"
                            )}
                            tag="div"
                          >
                            <_Builtin.Block
                              className={_utils.cx(
                                _styles,
                                "margin-bottom",
                                "margin-xsmall"
                              )}
                              tag="div"
                            >
                              <_Builtin.Block
                                className={_utils.cx(
                                  _styles,
                                  "home_committees-main_meta-wrapper"
                                )}
                                tag="div"
                              >
                                <_Builtin.Block
                                  className={_utils.cx(_styles, "tag")}
                                  tag="div"
                                >
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "text-size-tiny"
                                    )}
                                    tag="div"
                                  >
                                    {"Newsletter committee"}
                                  </_Builtin.Block>
                                </_Builtin.Block>
                              </_Builtin.Block>
                            </_Builtin.Block>
                            <_Builtin.Block tag="div">
                              <_Builtin.Block
                                className={_utils.cx(
                                  _styles,
                                  "margin-bottom",
                                  "margin-xxsmall"
                                )}
                                tag="div"
                              >
                                <_Builtin.Heading
                                  className={_utils.cx(
                                    _styles,
                                    "heading-style-h5"
                                  )}
                                  tag="h3"
                                >
                                  {"Tell your neighbors' stories"}
                                </_Builtin.Heading>
                              </_Builtin.Block>
                              <_Builtin.Block
                                className={_utils.cx(
                                  _styles,
                                  "text-size-regular"
                                )}
                                tag="div"
                              >
                                {
                                  "Bring neighbors together with well through events and connections."
                                }
                              </_Builtin.Block>
                            </_Builtin.Block>
                          </_Builtin.Block>
                        </_Builtin.Block>
                        <_Builtin.Block
                          className={_utils.cx(
                            _styles,
                            "home_committees-main_image-wrapper"
                          )}
                          tag="div"
                        >
                          <_Builtin.Image
                            className={_utils.cx(
                              _styles,
                              "home_committees-main_image"
                            )}
                            loading="lazy"
                            width="auto"
                            height="auto"
                            alt=""
                            src="https://cdn.prod.website-files.com/67f474b29211e3047d6a314e/67f48b519939effcfdec35a2_image1.jpeg"
                          />
                        </_Builtin.Block>
                      </_Builtin.Link>
                    </_Builtin.Block>
                  </_Builtin.SliderSlide>
                  <_Builtin.SliderSlide
                    className={_utils.cx(_styles, "home_committees-main_slide")}
                    tag="div"
                  >
                    <_Builtin.Block
                      className={_utils.cx(
                        _styles,
                        "home_committees-main_item"
                      )}
                      tag="div"
                    >
                      <_Builtin.Link
                        className={_utils.cx(
                          _styles,
                          "home_committees-main_item-link"
                        )}
                        button={false}
                        block="inline"
                        options={{
                          href: "#",
                        }}
                      >
                        <_Builtin.Block
                          className={_utils.cx(_styles, "absolute_shade")}
                          tag="div"
                        />
                        <_Builtin.Block
                          className={_utils.cx(
                            _styles,
                            "home_committees-main_item-content"
                          )}
                          tag="div"
                        >
                          <_Builtin.Block
                            className={_utils.cx(
                              _styles,
                              "home_committees-main_item-content-top"
                            )}
                            tag="div"
                          >
                            <_Builtin.Block
                              className={_utils.cx(
                                _styles,
                                "margin-bottom",
                                "margin-xsmall"
                              )}
                              tag="div"
                            >
                              <_Builtin.Block
                                className={_utils.cx(
                                  _styles,
                                  "home_committees-main_meta-wrapper"
                                )}
                                tag="div"
                              >
                                <_Builtin.Block
                                  className={_utils.cx(_styles, "tag")}
                                  tag="div"
                                >
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "text-size-tiny"
                                    )}
                                    tag="div"
                                  >
                                    {"Emergency Hub"}
                                  </_Builtin.Block>
                                </_Builtin.Block>
                              </_Builtin.Block>
                            </_Builtin.Block>
                            <_Builtin.Block tag="div">
                              <_Builtin.Block
                                className={_utils.cx(
                                  _styles,
                                  "margin-bottom",
                                  "margin-xxsmall"
                                )}
                                tag="div"
                              >
                                <_Builtin.Heading
                                  className={_utils.cx(
                                    _styles,
                                    "heading-style-h5"
                                  )}
                                  tag="h3"
                                >
                                  {"Support your neighbors in a crisis"}
                                </_Builtin.Heading>
                              </_Builtin.Block>
                              <_Builtin.Block
                                className={_utils.cx(
                                  _styles,
                                  "text-size-regular"
                                )}
                                tag="div"
                              >
                                {
                                  "Bring neighbors together with well through events and connections."
                                }
                              </_Builtin.Block>
                            </_Builtin.Block>
                          </_Builtin.Block>
                        </_Builtin.Block>
                        <_Builtin.Block
                          className={_utils.cx(
                            _styles,
                            "home_committees-main_image-wrapper"
                          )}
                          tag="div"
                        >
                          <_Builtin.Image
                            className={_utils.cx(
                              _styles,
                              "home_committees-main_image"
                            )}
                            loading="lazy"
                            width="auto"
                            height="auto"
                            alt=""
                            src="https://cdn.prod.website-files.com/67f474b29211e3047d6a314e/67f48b519939effcfdec35a2_image1.jpeg"
                          />
                        </_Builtin.Block>
                      </_Builtin.Link>
                    </_Builtin.Block>
                  </_Builtin.SliderSlide>
                  <_Builtin.SliderSlide
                    className={_utils.cx(_styles, "home_committees-main_slide")}
                    tag="div"
                  >
                    <_Builtin.Block
                      className={_utils.cx(
                        _styles,
                        "home_committees-main_item"
                      )}
                      tag="div"
                    >
                      <_Builtin.Link
                        className={_utils.cx(
                          _styles,
                          "home_committees-main_item-link"
                        )}
                        button={false}
                        block="inline"
                        options={{
                          href: "#",
                        }}
                      >
                        <_Builtin.Block
                          className={_utils.cx(_styles, "absolute_shade")}
                          tag="div"
                        />
                        <_Builtin.Block
                          className={_utils.cx(
                            _styles,
                            "home_committees-main_item-content"
                          )}
                          tag="div"
                        >
                          <_Builtin.Block
                            className={_utils.cx(
                              _styles,
                              "home_committees-main_item-content-top"
                            )}
                            tag="div"
                          >
                            <_Builtin.Block
                              className={_utils.cx(
                                _styles,
                                "margin-bottom",
                                "margin-xsmall"
                              )}
                              tag="div"
                            >
                              <_Builtin.Block
                                className={_utils.cx(
                                  _styles,
                                  "home_committees-main_meta-wrapper"
                                )}
                                tag="div"
                              >
                                <_Builtin.Block
                                  className={_utils.cx(_styles, "tag")}
                                  tag="div"
                                >
                                  <_Builtin.Block
                                    className={_utils.cx(
                                      _styles,
                                      "text-size-tiny"
                                    )}
                                    tag="div"
                                  >
                                    {"Advocacy committee"}
                                  </_Builtin.Block>
                                </_Builtin.Block>
                              </_Builtin.Block>
                            </_Builtin.Block>
                            <_Builtin.Block tag="div">
                              <_Builtin.Block
                                className={_utils.cx(
                                  _styles,
                                  "margin-bottom",
                                  "margin-xxsmall"
                                )}
                                tag="div"
                              >
                                <_Builtin.Heading
                                  className={_utils.cx(
                                    _styles,
                                    "heading-style-h5"
                                  )}
                                  tag="h3"
                                >
                                  {
                                    "Build a neighborhood that's home for everyone"
                                  }
                                </_Builtin.Heading>
                              </_Builtin.Block>
                              <_Builtin.Block
                                className={_utils.cx(
                                  _styles,
                                  "text-size-regular"
                                )}
                                tag="div"
                              >
                                {
                                  "Bring neighbors together with well through events and connections."
                                }
                              </_Builtin.Block>
                            </_Builtin.Block>
                          </_Builtin.Block>
                        </_Builtin.Block>
                        <_Builtin.Block
                          className={_utils.cx(
                            _styles,
                            "home_committees-main_image-wrapper"
                          )}
                          tag="div"
                        >
                          <_Builtin.Image
                            className={_utils.cx(
                              _styles,
                              "home_committees-main_image"
                            )}
                            loading="lazy"
                            width="auto"
                            height="auto"
                            alt=""
                            src="https://cdn.prod.website-files.com/67f474b29211e3047d6a314e/67f48b519939effcfdec35a2_image1.jpeg"
                          />
                        </_Builtin.Block>
                      </_Builtin.Link>
                    </_Builtin.Block>
                  </_Builtin.SliderSlide>
                </_Builtin.SliderMask>
                <_Builtin.SliderArrow
                  className={_utils.cx(
                    _styles,
                    "slider-arrow",
                    "is-bottom-previous"
                  )}
                  dir="left"
                >
                  <_Builtin.HtmlEmbed
                    className={_utils.cx(_styles, "slider-arrow-icon")}
                    value="%3Csvg%20width%3D%22100%25%22%20height%3D%22100%25%22%20viewBox%3D%220%200%2016%2016%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Cpath%20d%3D%22M3.31066%208.75001L9.03033%2014.4697L7.96967%2015.5303L0.439339%208.00001L7.96967%200.469676L9.03033%201.53034L3.31066%207.25001L15.5%207.25L15.5%208.75L3.31066%208.75001Z%22%20fill%3D%22currentColor%22%2F%3E%0A%3C%2Fsvg%3E"
                  />
                </_Builtin.SliderArrow>
                <_Builtin.SliderArrow
                  className={_utils.cx(
                    _styles,
                    "slider-arrow",
                    "is-bottom-next"
                  )}
                  dir="right"
                >
                  <_Builtin.HtmlEmbed
                    className={_utils.cx(_styles, "slider-arrow-icon")}
                    value="%3Csvg%20width%3D%22100%25%22%20height%3D%22100%25%22%20viewBox%3D%220%200%2016%2016%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Cpath%20d%3D%22M12.6893%207.25L6.96967%201.53033L8.03033%200.469666L15.5607%208L8.03033%2015.5303L6.96967%2014.4697L12.6893%208.75H0.5V7.25H12.6893Z%22%20fill%3D%22currentColor%22%2F%3E%0A%3C%2Fsvg%3E"
                  />
                </_Builtin.SliderArrow>
                <_Builtin.SliderNav
                  className={_utils.cx(
                    _styles,
                    "home_committees-main_slide-nav"
                  )}
                />
              </_Builtin.SliderWrapper>
              <_Builtin.Block
                className={_utils.cx(_styles, "show-mobile-landscape")}
                tag="div"
              >
                <_Builtin.Block
                  className={_utils.cx(_styles, "margin-top", "margin-xxlarge")}
                  tag="div"
                >
                  <_Builtin.Block
                    className={_utils.cx(_styles, "button-group", "is-right")}
                    tag="div"
                  >
                    <_Builtin.Link
                      className={_utils.cx(
                        _styles,
                        "button",
                        "is-secondary",
                        "white-text"
                      )}
                      button={true}
                      block=""
                      options={{
                        href: "#",
                      }}
                    >
                      {"View all"}
                    </_Builtin.Link>
                  </_Builtin.Block>
                </_Builtin.Block>
              </_Builtin.Block>
              <_Builtin.NotSupported _atom="DynamoWrapper" />
            </_Builtin.Block>
          </_Builtin.Block>
        </_Builtin.Block>
      </_Builtin.Block>
    </_Component>
  );
}
